/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type {
  BaseContract,
  BigNumberish,
  BytesLike,
  FunctionFragment,
  Result,
  Interface,
  EventFragment,
  AddressLike,
  ContractRunner,
  ContractMethod,
  Listener,
} from "ethers";
import type {
  TypedContractEvent,
  TypedDeferredTopicFilter,
  TypedEventLog,
  TypedLogDescription,
  TypedListener,
  TypedContractMethod,
} from "./common";

export declare namespace EHRRegistry {
  export type FileMetaStruct = {
    fileId: BigNumberish;
    category: string;
    timestamp: BigNumberish;
  };

  export type FileMetaStructOutput = [
    fileId: bigint,
    category: string,
    timestamp: bigint
  ] & { fileId: bigint; category: string; timestamp: bigint };
}

export interface EHRRegistryInterface extends Interface {
  getFunction(nameOrSignature: "getFiles" | "registerFile"): FunctionFragment;

  getEvent(nameOrSignatureOrTopic: "FileRegistered"): EventFragment;

  encodeFunctionData(
    functionFragment: "getFiles",
    values: [AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "registerFile",
    values: [string]
  ): string;

  decodeFunctionResult(functionFragment: "getFiles", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "registerFile",
    data: BytesLike
  ): Result;
}

export namespace FileRegisteredEvent {
  export type InputTuple = [
    patient: AddressLike,
    fileId: BigNumberish,
    category: string
  ];
  export type OutputTuple = [patient: string, fileId: bigint, category: string];
  export interface OutputObject {
    patient: string;
    fileId: bigint;
    category: string;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export interface EHRRegistry extends BaseContract {
  connect(runner?: ContractRunner | null): EHRRegistry;
  waitForDeployment(): Promise<this>;

  interface: EHRRegistryInterface;

  queryFilter<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;
  queryFilter<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;

  on<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    listener: TypedListener<TCEvent>
  ): Promise<this>;
  on<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    listener: TypedListener<TCEvent>
  ): Promise<this>;

  once<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    listener: TypedListener<TCEvent>
  ): Promise<this>;
  once<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    listener: TypedListener<TCEvent>
  ): Promise<this>;

  listeners<TCEvent extends TypedContractEvent>(
    event: TCEvent
  ): Promise<Array<TypedListener<TCEvent>>>;
  listeners(eventName?: string): Promise<Array<Listener>>;
  removeAllListeners<TCEvent extends TypedContractEvent>(
    event?: TCEvent
  ): Promise<this>;

  getFiles: TypedContractMethod<
    [_patient: AddressLike],
    [EHRRegistry.FileMetaStructOutput[]],
    "view"
  >;

  registerFile: TypedContractMethod<[_category: string], [void], "nonpayable">;

  getFunction<T extends ContractMethod = ContractMethod>(
    key: string | FunctionFragment
  ): T;

  getFunction(
    nameOrSignature: "getFiles"
  ): TypedContractMethod<
    [_patient: AddressLike],
    [EHRRegistry.FileMetaStructOutput[]],
    "view"
  >;
  getFunction(
    nameOrSignature: "registerFile"
  ): TypedContractMethod<[_category: string], [void], "nonpayable">;

  getEvent(
    key: "FileRegistered"
  ): TypedContractEvent<
    FileRegisteredEvent.InputTuple,
    FileRegisteredEvent.OutputTuple,
    FileRegisteredEvent.OutputObject
  >;

  filters: {
    "FileRegistered(address,uint256,string)": TypedContractEvent<
      FileRegisteredEvent.InputTuple,
      FileRegisteredEvent.OutputTuple,
      FileRegisteredEvent.OutputObject
    >;
    FileRegistered: TypedContractEvent<
      FileRegisteredEvent.InputTuple,
      FileRegisteredEvent.OutputTuple,
      FileRegisteredEvent.OutputObject
    >;
  };
}
