/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
export type { EHRAccess } from "./EHRAccess";
export type { EHRRegistry } from "./EHRRegistry";
export * as factories from "./factories";
export { EHRAccess__factory } from "./factories/EHRAccess__factory";
export { EHRRegistry__factory } from "./factories/EHRRegistry__factory";
