/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
export { EHRAccess__factory } from "./EHRAccess__factory";
export { EHRRegistry__factory } from "./EHRRegistry__factory";
