// MongoDB Schema Definitions for Healthcare EHR Platform
import mongoose from "mongoose";
import { ObjectId } from "mongodb";
export interface User {
  // In MongoDB this is typically an ObjectId, but parts of the codebase
  // also treat it as a string (after JSON serialization).
  _id: ObjectId | string
  email: string
  password: string // hashed
  name: string
  role: "patient" | "doctor" | "lab" | "admin"
  isVerified: boolean // For doctor/lab approval by admin
  isBlocked: boolean
  specialization?: string // For doctors
  licenseNumber?: string // For doctors and labs
  createdAt: Date
  updatedAt: Date
  blockchainAddress?: string // Thirdweb In-App Wallet address (unique, sparse index in MongoDB)
  encryptionPublicKey?: string
  /**
   * Server-side escrow for the RSA private key so decryption can work on any device.
   * Stored encrypted by server secret (see /api/auth/unified).
   */
  encryptionPrivateKeyEscrow?: {
    ivB64: string
    tagB64: string
    cipherB64: string
  }
  /** Patient profile — set during universal intake */
  dateOfBirth?: string
  bloodType?: string
  emergencyContact?: string
}

// export interface MedicalRecord {
//   _id: string
//   patientId: string
//   uploadedBy: string // userId of uploader (patient, doctor, or lab)
//   uploaderRole: "patient" | "doctor" | "lab"
//   fileName: string
//   fileType: string // pdf, jpg, png
//   fileUrl: string // Cloud storage URL
//   fileCID: string
//   fileHash: string // SHA-256 hash for blockchain verification
//   recordType: string // e.g., "Lab Report", "Prescription", "X-Ray"
//   uploadDate: Date
//   metadata?: {
//     description?: string
//     labName?: string
//     testType?: string
//   }
// }

// export interface MedicalRecord {
//   patientId: {
//     type: mongoose.Schema.Types.ObjectId,
//     ref: "User",
//     required: true,
//   },

//   uploadedBy: {
//     type: mongoose.Schema.Types.ObjectId,
//     ref: "User",
//     required: true,
//   },

//   fileName: {
//     type: String,
//     required: true,
//   },

//   cid: {
//     type: String,
//     required: true,
//   },

//   fileSize: Number,

//   createdAt: {
//     type: Date,
//     default: Date,
//   },
// }

export interface MedicalRecord {
  _id?: ObjectId
  patientId: ObjectId
  uploadedBy: ObjectId
  uploaderRole: "patient" | "doctor" | "lab"
  fileName: string

  // Pinata CID (preferred). Some older routes use mock_* fields.
  cid?: string
  fileCID?: string

  fileSize?: number
  fileType?: string
  fileUrl?: string
  fileHash?: string

  recordType: string
  description?: string
  metadata?: Record<string, any>

  // Different routes use different timestamp field names.
  createdAt?: Date
  uploadDate?: Date

  fileId: number , // The ID generated by EHRRegistry.sol
  transactionHash: string  // The real Quorum tx hash
    // ── Encryption fields ──────────────────────────────────────
    encryptedAESKey?: string            // ← ADD: AES key wrapped with patient's RSA public key
    aesIV?: string                      // ← ADD: base64 IV used in AES-GCM
    doctorKeys?: Record<string, string> // ← ADD: { doctorAddress → encrypted AES key for that doctor }
}

export interface AccessPermission {
  _id: string
  patientId: string
  grantedTo: string // userId of doctor or lab
  grantedToRole: "doctor" | "lab"
  accessLevel: "view" | "upload" | "view-upload" // Labs typically only have upload
  grantedAt: Date
  revokedAt?: Date
  isActive: boolean
  blockchainTxHash?: string // Reference to blockchain transaction
}

export interface AISummary {
  _id: string
  recordId: string
  patientId: string
  summary: {
    diagnosis?: string
    medications?: string[]
    testResults?: Array<{
      test: string
      value: string
      unit?: string
      normalRange?: string
    }>
    recommendations?: string[]
    keyFindings: string[]
  }
  generatedAt: Date
  modelUsed: string
}

export interface AuditLog {
  _id: string
  action: "grant_access" | "revoke_access" | "view_record" | "upload_record" | "download_record"
  performedBy: string // userId
  performedByRole: "patient" | "doctor" | "lab" | "admin"
  targetUserId?: string // For access grants/revokes
  recordId?: string // For record operations
  patientId: string
  timestamp: Date
  ipAddress?: string
  blockchainTxHash?: string
  metadata?: Record<string, any>
}

export interface Followup {
  _id?: ObjectId | string
  patientId: ObjectId | string
  doctorId: ObjectId | string
  doctorName: string
  doctorSpecialization: string
  action: "view" | "upload" | "observation"
  recordId?: string
  description: string
  timestamp: Date
}
